# NumPy Indexing and Selection

Here we will discuss how to select elements or groups of elements from an array.

In [1]:
import numpy as np

In [4]:
#Creating sample array
np.random.seed(41)
arr=np.random.randint(0,50,10)
arr

array([ 0, 35, 12, 34, 16,  1, 25, 23, 21, 26])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [5]:
len(arr)

10

In [6]:
arr[-1]

26

In [7]:
#Get a value at an index
arr[9]

26

In [8]:
#Get values in a range
arr[1:8:2]

array([35, 34,  1, 23])

### Filtering

In [9]:
# Filtering condition 
arr=np.array([1,2,1010,4,108,18,71,610])
arr

array([   1,    2, 1010,    4,  108,   18,   71,  610])

In [10]:
arr<100

array([ True,  True, False,  True, False,  True,  True, False])

In [11]:
arr[arr<100]  #Gives the actual value where condition is true

array([ 1,  2,  4, 18, 71])

In [12]:
np.where(arr<100) # where function outputs index location of values where the
# condition is True

(array([0, 1, 3, 5, 6], dtype=int64),)

In [ ]:
np.where(arr>100)

In [ ]:
np.where(arr==100)

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. It is recommended to use the comma notation for clarity.

In [13]:
arr_2d = np.array(([1,2,3],[12,15,18],[64,96,128]))
arr_2d

array([[  1,   2,   3],
       [ 12,  15,  18],
       [ 64,  96, 128]])

In [ ]:
arr_2d[2,:]  # Indexing Last row

In [ ]:
arr_2d[[0,2,1],2:3]

In [ ]:
arr_2d[:,[2]] # Indexing 3rd column

In [ ]:
arr_2d[1:,1:]

In [ ]:
arr_2d[1,1]

In [ ]:
arr_2d[0:2][0:2]

In [ ]:
# Indexing column
arr_2d[:,2]

In [ ]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

In [ ]:
arr_2d[[2,0,1],1:]

In [ ]:
arr_2d[0,-1::-1]

In [ ]:
arr_2d[0,[2,1,0]]

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [ ]:
arr1=np.ones((10,10))
arr1.shape

In [ ]:
#Set up matrix
arr2d = np.zeros(arr1.shape)  # taking shape from an existing array

In [ ]:
arr2d

In [ ]:
arr2d.shape

In [ ]:
no_of_rows=arr2d.shape[0]  # indexing the shape tuple

In [ ]:
#Set up array

for i in range(no_of_rows):
    arr2d[i] = i
    
arr2d

Fancy indexing allows the following

In [ ]:
arr2d[[6,3,8]]

In [ ]:
arr2d[:,[2,4,6,8]]

In [ ]:
#Allows in any order
arr2d[[6,4,2,7]]

# Happy Learning!